" zinglax's .vimrc file

" LINE NUMBERS
set nu

" PLUGINS
" vim-plug (https://github.com/junegunn/vim-plug)
" installation: 
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
"     https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
" Then to install plugins
" :PlugInstall
"
" PLUGINS BEGIN
call plug#begin('~/.vim/plugged')

" NERDTree
Plug 'https://github.com/scrooloose/nerdtree.git'

" NERDTree git status
" Plug 'Xuyuanp/nerdtree-git-plugin'

" AirLine (status bar)
Plug 'vim-airline/vim-airline'

" Tag Bar
" sudo apt-get install 
Plug 'https://github.com/majutsushi/tagbar'

" Ansible VIM Syntax
" Plug 'pearofducks/ansible-vim'

" Emmet-vim (HTML Editing)
" Plug 'mattn/emmet-vim'

" Git Gutter (VIM Git Highlighter)
Plug 'airblade/vim-gitgutter'

" Git NERDTree Highlighting
" Plug 'Xuyuanp/nerdtree-git-plugin'

" SVN NERDTree Highlighting
" Plug 'greggerz/nerdtree-svn-plugin'

" Using plug
Plug 'dylanaraps/wal.vim'

" PLUGINS END
call plug#end()


" NERDTree 
" open a NERDTree automatically when vim starts up
" autocmd vimenter * NERDTree

" open a NERDTree automatically when vim starts up if no files were specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" open NERDTree automatically when vim starts up on opening a directory
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif

" open NERDTree with Ctrl+n
map <C-n> :NERDTreeToggle<CR>


" close vim if the only window left open is a NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif



" TagBar
nmap <F8> :TagbarToggle<CR>

" HTML Tidy up command
" set sw=2 | %s/>/>\r/ | execute 'normal gg=G' | set nohlsearch | g/^\\s*\$/d


" Paste Toggle
" Tap this button when you wanna paste something into the vim editor
set pastetoggle=<F3>

" Folding 
" based on indentation level, create folds (perfect for python being
" whitespace delimited, make sure to write json files with indentation as
" well)
set foldmethod=indent

" THEME
" color koehler
color wal


" CURSOR LINE
set cursorline
hi CursorLine ctermbg=7 ctermfg=0

" CURSOR COLUMN
set cursorcolumn
hi CursorColumn ctermbg=7 ctermfg=0


